version: 0.2
phases:
  install:
    commands:
      - echo "Installing Terraform..."
      - curl -fsSL https://releases.hashicorp.com/terraform/1.9.5/terraform_1.9.5_linux_amd64.zip -o terraform.zip
      - unzip terraform.zip && mv terraform /usr/local/bin/ && terraform -version
  build:
    commands:
      - cd ..
      - terraform init -input=false
      - terraform apply -auto-approve
