name: Backsync UAT to Main

on:
  push:
    branches:
      - uat

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh

      - name: Fetch main branch
        run: |
          git fetch origin main:main

      - name: Create PR from uat to main
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          # Attempt to create PR; if it exists, just print message
          gh pr create \
            --base main \
            --head uat \
            --title "Backsync UAT changes to Main" \
            --body "Automated PR to merge latest UAT changes into Main branch." \
            --label "auto-sync" || echo "PR may already exist"
