name: Backsync UAT to Dev

on:
  push:
    branches:
      - uat

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh

      - name: Fetch dev branch
        run: |
          git fetch origin dev:dev

      - name: Create PR from uat to dev
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          gh pr create \
            --base dev \
            --head uat \
            --title "Backsync UAT changes to Dev" \
            --body "Automated PR to merge latest UAT changes into Dev branch." \
            --label "auto-sync" || echo "PR may already exist"
