name: Create PR from UAT to Main
on:
  push:
    branches:
      - uat

jobs:
  create-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if PR already exists
        id: check-pr
        run: |
          existing_pr=$(gh pr list --base main --head uat --state open --json number --jq '.[0].number // empty')
          if [ -n "$existing_pr" ]; then
            echo "pr_exists=true" >> $GITHUB_OUTPUT
            echo "pr_number=$existing_pr" >> $GITHUB_OUTPUT
            echo "Existing PR found: #$existing_pr"
          else
            echo "pr_exists=false" >> $GITHUB_OUTPUT
            echo "No existing PR found"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        if: steps.check-pr.outputs.pr_exists == 'false'
        run: |
          gh pr create \
            --base main \
            --head uat \
            --title "🔄 Back sync: UAT → Main" \
            --body "Automated back sync PR to merge UAT changes into Main.
            
            **Latest UAT commit:** ${{ github.sha }}
            **Triggered by:** Push to UAT branch" \
            --label auto-sync
          echo "✅ Pull request created successfully"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}